### ISSUE TITLE
open/close と write が衝突して音が出ないケースがある

### ISSUE THREAD

**Issue by moveccr** [isaki68k/netbsd-src#116]
VirtualBox 5.2.26 amd64 host, i386 guest

% cat p
echo O4CDEFGABO5C > /dev/speaker

% (audioplay pyon_15625.wav ; audioplay pyon_15625.wav) & sh p

とすると B 以降の音が出ない。そのときのログ：

audio_close@0 {#427,} pid=1000.1 po=2 ro=0
audio0: device timeout
audio0: device timeout
audioplay: audio device write failed: Undefined error: 0
audio_close@0 {#426,} pid=1667.1 po=1 ro=0
audio_open@0 dev=audio flags=0x2 po=1 ro=0
audio track#428 play mode: slinear_le 16bit 1ch 48000Hz
TRIANGLE: period=440, pitch=2093
audio_close@0 {#428,} pid=1000.1 po=2 ro=0
audio0: device timeout
audio0: device timeout

**Comment by isaki68k** [comment]
VirtualBox 5.2.26(on Windows10)、guest amd64-current、
hdafg (HDaudio) だと echo CDE > /dev/speaker だけでもなんかおかしい。
auich (Intel) だと起きないので、VirtualBox側の問題?

**Comment by isaki68k** [comment]
たぶん VirtualBox の問題。
