### ISSUE TITLE
32bit 内部表現

### ISSUE THREAD

**Issue by moveccr** [isaki68k/netbsd-src#12]
コンパイル時選択肢は用意してあるがどうするかな？

**Comment by isaki68k** [comment]
計算自体は ifdef で用意できる(してある)が、
ミキサーでのMDエンコード/デコードルーチンも16bit/32bit用それぞれ
用意しないといけなくなり、現実的でない気がする。

**Comment by isaki68k** [comment]
誰かがやってたような気がする。
