### ISSUE TITLE
リングバッファと単純バッファを分離する

### ISSUE THREAD

**Issue by moveccr** [isaki68k/netbsd-src#2]
#1 で uiomove が入力用リングバッファにアクセスするようにすれば、リングバッファは、トラックに関して言えば input と output の2本あればよく、中間の変換バッファはカウントだけが動く単純バッファでよい。そして単純バッファのサンプル型は内部表現の型で固定される。

**Comment by isaki68k** [comment]
この通りかどうかは分からんけど、おおむねいい感じで動作している。
